### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ladyomega** [thecodemonkey86/qt_mysql_driver#12]
Any chance there's an update video on how to properly do it? It's not working on my end.

**Comment by thecodemonkey86** [comment]
Hi, I'm gonna need more information what exactly does not work, which version you use, what you have tried so far, etc.
Maybe there are some hints in the console output, if you set the QT_DEBUG_PLUGINS environment variable to value = 1, in Qt Creator project run settings:
![image](https://user-images.githubusercontent.com/11927938/117187458-39427880-addc-11eb-8410-c0e70f573bd5.png)

**Comment by ladyomega** [comment]
thanks for getting back to me!
I was using QT 6.0.3. But Now I'm trying to make it work on an older version (5.11).
The console output was always the same: QMYSQL driver not loaded.
I have tried to put the files on the bin folder, as well as the project folder and none worked.
Since I'm fairly new to QT, I'm thinking that I must be missing something on how to do the proper set up.
I'm doing this for my honors project at college, is there anyway you could walk me trough this set up if you're available?
Like a paid one hour tutoring?

**Comment by thecodemonkey86** [comment]
Actually there is not that much to set up. You only need to make sure that you use the correct version of the files provided here (Matching Qt version, matching compiler: MSVC or MinGW, and matching bitness: 32 bit or 64 bit. For example I don't provide the SQL driver files for Qt 5.11 (since it is outdated). I show you screenshots of my sample project:

In this example I set the Qt version to 6.0.4 and MSVC 64 bit compiler
![image](https://user-images.githubusercontent.com/11927938/117346253-cd2d4680-aea7-11eb-811b-86a3c13aab71.png)
in that case you require the corresponding files from [here](https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_6.0.4)
![image](https://user-images.githubusercontent.com/11927938/117346496-1aa9b380-aea8-11eb-8323-021120a8e582.png)

The debug build directory looks like this
![image](https://user-images.githubusercontent.com/11927938/117348165-2e561980-aeaa-11eb-972d-3ddb8e8ad7e5.png)

and contains the project executable (in my case qttest2.exe), libmysql.dll, libcrypto-1_1-x64.dll, libssl-1_1-x64.dll plus a subdirectory "sqldrivers" that contains the debug build of qsqlmysqld.dll

![image](https://user-images.githubusercontent.com/11927938/117347004-ca7f2100-aea8-11eb-884e-c17ee6448bac.png)

That should be all to set up

**Comment by ladyomega** [comment]
I have followed the instructions, and this is how my project looks like:
![image](https://user-images.githubusercontent.com/68204412/117355544-b8898800-ae80-11eb-851a-afe06815bd1b.png)

Now, QMYSQL appears on the list of the drivers, but still doesn't load.

![image](https://user-images.githubusercontent.com/68204412/117356002-45344600-ae81-11eb-8265-849f80288d51.png)

**Comment by ladyomega** [comment]
So I've just realized, that since when I tried with the 5.11 didn't work. I reinstalled the latest version, an in a matter of days it went from 6.0.3 to 6.0.4 to 6.1.0 (which is my current version). This is probably why I'm getting the drivers listed but not loading, correct?

**Comment by thecodemonkey86** [comment]
I did't make a release for version 6.1.0 yet, so it can't be used just yet

**Comment by ladyomega** [comment]
Got it! I'm already happy that the drivers are showing on the list. That's progress! I'll be on the look out for your next release so I can try again. Thank you so much!

**Comment by thecodemonkey86** [comment]
The release for 6.1.0 MinGW is [here](https://github.com/thecodemonkey86/qt_mysql_driver/files/6437778/qsqlmysql.dll_Qt_SQL_driver_6.1.0_MinGW_8.1.0_64-bit.zip)

**Comment by ladyomega** [comment]
It WORKED! You are the best!!!
Thank you so much! You saved my school project. <3

**Comment by thecodemonkey86** [comment]
I'm glad I could help
