### ISSUE TITLE
qt_mysql_driver for Qt 5.13.2

### ISSUE THREAD

**Issue by aureyoboss** [thecodemonkey86/qt_mysql_driver#4]
Hello,

I can't find the driver for Qt 5.13.2. Is this normal?
Thank you.

Regards.

**Comment by thecodemonkey86** [comment]
Hi,

well, I assumed no one would need a 5.13.2 (no long term support like 5.12) release, because 5.14 was already out when I started this, and now 5.13 not  supported anymore by Qt themselves.

Anyway, I made a 5.13.2 release
https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.13.2

**Comment by aureyoboss** [comment]
Thank you thecodemonkey86 !
