### ISSUE TITLE
5.13.2 version MinGw 32-bit

### ISSUE THREAD

**Issue by CppProgrammer23** [thecodemonkey86/qt_mysql_driver#5]
Hi!
I tried this version (in the title) but I faced a problem, the QMYSQL not loaded. Is there anything special with this version? Because I saw this: "32-Bit (since there is no 32-Bit MySQL server version 8.0, bundled with libmysql 5.7)"

**Comment by thecodemonkey86** [comment]
Hi, 
well, "(since there is no 32-Bit MySQL server version 8.0, bundled with libmysql 5.7)" simply means that Oracle does not offer a 32-bit version of libmysql.dll version 8.0, the last version libmysql.dll is actually v6.1, which is also provided in the zip file (5.7 refers to the maximum target MySQL server version, so it probably does not fully work with 8.0). I checked, the provided version for Qt 5.13.2 MinGW works for me. Maybe you require the libraries from OpenSSL additionally? You should also check the environment variable QT_DEBUG_PLUGINS described here https://doc.qt.io/qt-5/deployment-plugins.html and probably on forum.qt.io (didn't check though)

**Comment by CppProgrammer23** [comment]
_**Thanks**_
